### ISSUE TITLE
Input in textboxes are not properly validated!

### ISSUE THREAD

**Issue by ooplearner** [kavedweller/MathPracticeGUI#2]
Not all exceptions are handled in textboxes. For example, input something and then delete leaves the boxes empty and causes unhandled exception when converted to integer. Pasting non-digit strings from clipboard is also possible causing undesired output.

**Comment by kavedweller** [comment]
Yes, I was aware of the 'pasting issue' and thought about it but yet to figure out something. The empty string issue shouldn't be too difficult to deal with. I'll address these issues as soon as I can. Thanks!
